model_params:
  dim: 16
  init_dim: 16
  dim_mults: [ 1, 2, 4, 8]
  channels: 3
  resnet_block_groups: 8
  learned_sinusoidal_cond: False
  random_fourier_features: False
  learned_sinusoidal_dim: 16
  
data_params:
  data_path: "data/"
  train_batch_size: 4
  test_batch_size:  4
  num_workers: 4
  pin_memory: True
  
exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  device: 'cuda'
  save_dir: "logs"
  version: 'v4.1_U'

train_params:
  max_epochs: 800
  use_wandb: True
  seeds: 2024

