model_params:
  channels: 3
  img_size: 224
  embed_dim: 1600
  input_shape: (3, 224, 224)
  
data_params:
  data_path: "data/"
  train_batch_size: 4
  test_batch_size:  4
  num_workers: 4
  pin_memory: True
  
exp_params:
  projLR: 0.005
  dscLR: 0.01
  dsc_margin: 0.5
  weight_decay: 0.0
  scheduler_gamma: 0.95
  device: 'cuda'
  save_dir: "logs"
  version: 'SimpleNet_v0.1'

train_params:
  max_epochs: 300
  use_wandb: False
  seeds: 2024

